# Generated by Django 4.0 on 2022-01-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
