# Generated by Django 4.0 on 2022-01-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
